### ISSUE TITLE
Descreasing Cart Count (Visitor)

### ISSUE THREAD

**Issue by jude-lawson** [jude-lawson/bike-share#23]
- As a visitor,
  - When I visit `/cart`,
    - I see my item with a quantity of 1,
- * -
- When I decrease the quantity, 
  - My current page should be `/cart`,
  - The item's quantity should reflect the decrease,
  - The subtotal for that item should decrease,
  - The total for the cart should match that decrease.

Child of #15
Requires #77

**Comment by justinetroyke** [comment]
Jude will implement

**Comment by justinetroyke** [comment]
Zach will review
