### ISSUE TITLE
Cart Checkout (Registered User)

### ISSUE THREAD

**Issue by jude-lawson** [jude-lawson/bike-share#27]
- As a registered user,
  - After adding a few items to my cart,
    - When I visit `/cart`,
    - And click `Checkout`,
      - I see my own dashboard,
      - I also see a flash message telling me I have ```Successfully submitted your order totaling $TOTAL```.

Child of #15
Blocked by #25

**Comment by justinetroyke** [comment]
Zach implementing

**Comment by justinetroyke** [comment]
Justine will review

**Comment by jude-lawson** [comment]
I'm gonna go ahead and assume that the cart count should be reset to zero after checking out and then returning to the dashboard.
