### ISSUE TITLE
Viewing All Accessories (Admin)

### ISSUE THREAD

**Issue by jude-lawson** [jude-lawson/bike-share#48]
- As an admin user,
  - When I visit `/admin/dashboard`,
    - I see a link for viewing all accessories,
    - When I click that link,
      - My current path should be `/admin/bike-shop`,
      - I see a table with all accessories (active and inactive)

Each accessory should have:

- A thumbnail of the image
 - Description
 - Status
 - Ability to Edit accessory
 - Ability to Retire/Reactivate accessory

Child of #51
Blocked by #49
Blocked by #45

**Comment by zdcthomas** [comment]
@justinetroyke adopts
