### ISSUE TITLE
Creating Accessories (Admin)

### ISSUE THREAD

**Issue by jude-lawson** [jude-lawson/bike-share#50]
- As an admin user,
  - When I visit admin bikeshop new
    - I can create an accessory,

An accessory must have 
- a title
- a description
- a price

- The title and description cannot be empty,
- The title must be unique for all accessories in the system,
- The price must be a valid decimal numeric value and greater than zero,
- The photo is optional. If not present, a stand-in photo is used. (PAPERCLIP)

Child of #51
Blocked by #45

**Comment by jude-lawson** [comment]
Blocked by #45

**Comment by zdcthomas** [comment]
Zach will implement

**Comment by zdcthomas** [comment]
Justine will review

**Comment by jude-lawson** [comment]
To complete this story:
- Need to make a default path for image file
- Need to verify that title and description are not empty
- Need to verify that the title is unique

**Comment by jude-lawson** [comment]
Just taking notes for myself: http://guides.rubyonrails.org/active_record_validations.html#numericality
